version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "w8fyz"
      - "maxwgamer"
    assignees:
      - "w8fyz"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "gradle"
